# Generated by Django 5.2.3 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuspiciousContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("misinformation", "Misinformation"),
                            ("hatespeech", "Hate Speech"),
                            ("harassment", "Harassment"),
                            ("spam", "Spam"),
                            ("fake", "Fake"),
                            ("news", "News"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("twitter", "Twitter"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/evidence/"
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
