# Generated by Django 5.2.3 on 2025-08-31 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsuspeciouscontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspiciouscontentreport',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence score for the detection (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='location',
            field=models.CharField(blank=True, help_text='Geographic location (Cameroon city/region)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='post_id',
            field=models.CharField(blank=True, help_text='Original post ID from the platform', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suspiciouscontentreport',
            name='user_id',
            field=models.CharField(blank=True, help_text='User ID who posted the content', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suspiciouscontentreport',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the content was reported/detected'),
        ),
        migrations.AddIndex(
            model_name='suspiciouscontentreport',
            index=models.Index(fields=['date_reported'], name='suspicious__date_re_18d737_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouscontentreport',
            index=models.Index(fields=['content_type'], name='suspicious__content_94c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouscontentreport',
            index=models.Index(fields=['urgency_level'], name='suspicious__urgency_653895_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouscontentreport',
            index=models.Index(fields=['platform'], name='suspicious__platfor_56611a_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouscontentreport',
            index=models.Index(fields=['location'], name='suspicious__locatio_6202ab_idx'),
        ),
        migrations.AlterModelTable(
            name='suspiciouscontentreport',
            table='suspicious_content_reports',
        ),
    ]
