# Generated by Django 5.2.2 on 2025-06-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
