# Generated by Django 5.2.3 on 2025-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_facebookpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=255)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                ("platform", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/evidence/"
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
