# Generated by Django 5.2.3 on 2025-06-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_suspiciouscontentreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("misinformation", "Misinformation"),
                            ("hatespeech", "Hate Speech"),
                            ("harassment", "Harassment"),
                            ("spam", "Spam"),
                            ("fake", "Fake"),
                            ("news", "News"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("twitter", "Twitter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "contact_information",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
