# Generated by Django 5.2.3 on 2025-06-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_reportcontent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportContent",
        ),
        migrations.DeleteModel(
            name="SuspiciousContentReport",
        ),
    ]
