# Generated by Django 5.2.3 on 2025-06-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_delete_reportcontent_delete_suspiciouscontentreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModelAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("is_harmful", models.BooleanField(default=False)),
                ("confidence", models.FloatField(null=True)),
                ("severity", models.CharField(max_length=20, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("explanation", models.TextField(blank=True)),
                ("detected_keywords", models.JSONField(blank=True, default=list)),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_analyses",
                        to="monitoring.facebookpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_type"], name="monitoring__analysi_b32967_idx"
                    ),
                    models.Index(
                        fields=["is_harmful"], name="monitoring__is_harm_b5580a_idx"
                    ),
                ],
            },
        ),
    ]
